version: '3'
services:
  back-end:
    container_name: 'back-end'
    build:
      context: ./back-end
      dockerfile: Dockerfile.node
    ports:
      - '3000:3000'
    networks:
      - front-end
  front-end:
    container_name: 'front-end'
    build:
      context: ./front-end
      dockerfile: Dockerfile.angular
    ports:
      - '8080:8080'
      - '80:80'
    depends_on:
      - back-end
    networks:
      - front-end

networks:
  front-end:
    external: true
    name: front-end
    driver: bridge
  back-end:
    external: true
    name: back-end
    driver: bridge